<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Cookies.aspx.cs" Inherits="Credentialing.Web.Cookies" MasterPageFile="~/Main.Master" %>
<asp:Content ContentPlaceHolderID="mainContent" runat="server">
    <h1>Cookies</h1>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean hendrerit aliquam aliquam. Ut pretium turpis accumsan metus tempus varius. Proin tempor fermentum lacus, et maximus ligula gravida fringilla. Sed placerat vehicula ante et lobortis. Fusce a mi dolor. Nullam at interdum sapien. Nam vitae quam purus. In turpis purus, ullamcorper nec tortor sed, hendrerit elementum magna. Aenean congue purus mauris, sed condimentum ante aliquet placerat. Aliquam pharetra mauris ac placerat sodales. Mauris malesuada est id sapien posuere, sed egestas dui fringilla. Aenean ipsum nulla, vehicula ut rutrum sed, pellentesque quis erat.</p>
    <p>Nulla tincidunt ullamcorper neque eget sagittis. Integer feugiat risus sit amet mi blandit vehicula. Cras malesuada convallis arcu, sit amet pulvinar odio blandit non. Nullam cursus condimentum mauris lacinia blandit. Sed porta quis enim in vulputate. Cras viverra lacus leo, ut dignissim magna elementum ac. Mauris arcu augue, rutrum at libero eget, ullamcorper volutpat enim. Aliquam efficitur velit vitae ante pharetra laoreet. Cras eros nulla, convallis vitae tellus ut, mollis consectetur quam. Vestibulum mollis nunc quam, non lacinia velit posuere non. Pellentesque venenatis felis nec eros finibus laoreet. Sed sed bibendum mauris.</p>
    <p>Nam faucibus nisi lacus, nec blandit nulla pulvinar quis. Nunc pulvinar nunc erat, ut ullamcorper lacus egestas sit amet. Nam dictum quis neque in luctus. Aliquam et ultricies massa. Mauris tristique tortor vulputate ligula imperdiet vulputate. Donec mauris lacus, faucibus in finibus ac, interdum in ex. Morbi semper neque a sapien mollis, dictum mollis odio scelerisque. Praesent porta, mi at blandit imperdiet, ipsum nisl ornare risus, a volutpat nunc lectus nec neque. Nam ac venenatis diam, quis sollicitudin lorem. Curabitur eu justo metus. Pellentesque neque lacus, viverra at lacus eu, porta venenatis libero. Proin consequat auctor fringilla. Nullam non turpis eros.</p>
    <p>Aliquam feugiat ante a posuere sollicitudin. Integer placerat accumsan risus at luctus. Donec quis quam eget erat euismod pretium. Aliquam maximus lectus velit, egestas gravida nisl dapibus egestas. Vivamus tempus ex auctor ultrices tristique. Pellentesque mi metus, accumsan a sodales et, convallis non velit. Duis a dictum felis, vitae fringilla risus. Aliquam et laoreet eros. Quisque quis interdum nunc. Phasellus molestie nisl id semper commodo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris congue nisl elit, a venenatis justo dignissim quis. Etiam lectus magna, tincidunt a enim eget, vestibulum euismod nisl. Nulla vehicula volutpat arcu, at hendrerit felis hendrerit accumsan. Nunc placerat at velit quis facilisis.</p>
    <p>Fusce a dignissim nulla, vel ultrices augue. Suspendisse potenti. Sed sed sem at magna lacinia malesuada eget quis tortor. Suspendisse a ultricies felis. Duis gravida nunc ac sollicitudin hendrerit. Morbi id eros at metus luctus aliquet. Duis eros tellus, porttitor ac dolor ac, volutpat viverra nibh. In volutpat pretium magna sit amet tempor. Duis ultrices magna consequat, dictum urna at, fermentum turpis. Sed vestibulum viverra dolor ut maximus. Cras hendrerit blandit tellus, at interdum velit hendrerit sed. </p>
</asp:Content>
