<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PrivacyPolicy.aspx.cs" Inherits="Credentialing.Web.PrivacyPolicy" MasterPageFile="~/Main.Master" %>

<asp:Content ContentPlaceHolderID="mainContent" runat="server">
    <h1>Privacy Policy</h1>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sed suscipit purus, sit amet lacinia lacus. Aenean mollis, erat vitae ornare feugiat, justo tortor pellentesque lectus, ac sodales mauris odio nec neque. Sed ultrices ornare urna, eget blandit augue vulputate id. Praesent facilisis, sapien sed sodales semper, diam nibh pellentesque eros, vehicula pellentesque tortor nunc sagittis tortor. Mauris odio neque, mollis nec ligula in, aliquet ultricies ante. Vestibulum sit amet nisl massa. In ac magna erat. Quisque luctus porta neque, non dictum felis finibus sed. Pellentesque pretium suscipit lorem, vel laoreet lacus. Donec imperdiet tincidunt urna, a pellentesque elit. Vestibulum congue augue vel eros bibendum, ac mattis mi pulvinar.</p>
    <p>Vivamus eu est ut nisi dictum lobortis et vel nibh. In ac nulla a urna dignissim pretium vel eget massa. Vivamus facilisis blandit nisi sit amet congue. Morbi egestas scelerisque sagittis. Fusce pretium molestie volutpat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dictum suscipit lacinia.</p>
    <p>Quisque ut odio at massa luctus rutrum a eu libero. Pellentesque et lacus at tortor iaculis vulputate vitae vitae arcu. Maecenas sit amet pulvinar ante. Vestibulum malesuada dolor ac purus maximus, ut dignissim sem suscipit. Aenean tincidunt nibh eu pharetra ultrices. Proin sollicitudin arcu nec semper ornare. Nullam sapien massa, pulvinar vitae massa vulputate, egestas aliquet dolor. Sed mi dolor, consequat vitae magna a, posuere volutpat lorem. Nulla pharetra accumsan mi, eu viverra metus gravida sit amet. Sed scelerisque dui sit amet aliquam volutpat. Pellentesque in turpis eu ante cursus consequat. Mauris consectetur convallis felis vel aliquam.</p>
    <p>Praesent sit amet dignissim purus. Sed lacus ipsum, mollis a tortor euismod, lobortis commodo risus. Morbi fringilla porttitor nisl, vitae molestie nulla maximus a. Morbi eget vestibulum quam. Integer quis tristique leo. Mauris pharetra dapibus velit eget malesuada. Proin vitae turpis vel mauris condimentum auctor et sed nunc. Quisque ex lectus, vestibulum sed tristique vel, convallis non turpis. Aliquam ut luctus nibh, et porttitor turpis. Mauris vulputate mi vitae dolor lacinia, vitae facilisis tellus pretium. Aliquam quis ipsum malesuada orci fringilla mollis at eu nisi. Sed in ultricies mauris. Nulla pulvinar ultrices nisi, in gravida tellus sodales eu. Sed id lorem fringilla, pretium est id, consectetur orci.</p>
    <p>In hac habitasse platea dictumst. Donec ut interdum nunc, sed tincidunt elit. Maecenas mauris neque, pharetra nec sagittis ut, interdum mollis eros. Duis semper diam a eros pellentesque, ac faucibus metus accumsan. Praesent quis ante nisl. Donec at placerat velit. Praesent maximus, risus nec imperdiet egestas, orci dolor tincidunt orci, sit amet luctus urna mi sed justo. Phasellus dictum diam sit amet ex scelerisque, vel bibendum ligula placerat. Vivamus dapibus erat et lacus condimentum mattis. Proin in nunc tellus. </p>
</asp:Content>