<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="TermsConditions.aspx.cs" Inherits="Credentialing.Web.TermsConditions" MasterPageFile="~/Main.Master" %>

<asp:Content ContentPlaceHolderID="mainContent" runat="server">
    <h1>Terms and conditions</h1>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum finibus ex sit amet placerat ultrices. Quisque ullamcorper nunc vitae arcu dignissim, et maximus justo elementum. Duis suscipit euismod elit, sit amet hendrerit erat dapibus id. Quisque lacinia commodo lectus, ut dignissim justo fringilla ut. Ut ultrices felis quis vehicula commodo. Morbi laoreet viverra justo a ullamcorper. Quisque tincidunt neque sed ipsum vestibulum venenatis. Phasellus vel tempus odio. Curabitur luctus mi vitae lobortis ullamcorper. Proin sed erat in augue accumsan rhoncus. Nulla facilisi. Praesent ultricies placerat dolor. Phasellus at ipsum et augue iaculis fermentum. Aliquam id metus vel urna lobortis luctus.</p>
    <p>Quisque tristique vehicula tincidunt. Etiam vel dignissim dolor. Mauris posuere nulla quam, a dictum lorem ultrices nec. Ut maximus eu velit nec faucibus. Quisque varius facilisis ante a imperdiet. Nullam mattis non ante ut fermentum. Fusce vehicula, arcu id blandit fermentum, velit tortor finibus risus, quis condimentum libero lacus ac metus. Nulla a nunc enim. Vivamus quis fermentum quam. Praesent rutrum ut ipsum ut vehicula. Integer vestibulum id ligula nec accumsan. Suspendisse iaculis, neque nec consequat scelerisque, nisi augue auctor orci, eu imperdiet lacus sapien a justo. Vivamus convallis magna et lobortis ultrices. Vivamus at magna consectetur nibh vestibulum pulvinar at at velit. Quisque nec rhoncus nibh.</p>
    <p>Aliquam erat volutpat. Etiam quis varius orci. Sed ornare nulla malesuada, tincidunt nibh et, efficitur nisl. Aenean nec pellentesque ipsum. Fusce at consectetur metus, vitae ultricies dui. Mauris venenatis dui bibendum, accumsan diam sed, consectetur augue. Ut dapibus aliquam diam lacinia tempus. In at neque accumsan, dapibus turpis a, malesuada mi. Ut nec tempus purus. Phasellus sit amet consequat arcu. Quisque velit felis, posuere quis gravida sit amet, dictum eu quam. Fusce euismod venenatis facilisis.</p>
    <p>Etiam ullamcorper tortor in ligula blandit, eu ultrices neque congue. In ut nisl et mauris interdum iaculis. Aliquam suscipit ac dolor eu ultrices. Quisque feugiat imperdiet dignissim. Aenean dapibus lacinia diam ut molestie. Nulla suscipit ante ut mi efficitur tristique. Curabitur non mauris quis turpis blandit ornare. Suspendisse vitae lacus eget augue gravida rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
    <p>Nullam vehicula eros in auctor ullamcorper. Proin maximus sagittis varius. Integer velit quam, interdum et efficitur et, faucibus nec risus. Nam efficitur velit a tellus imperdiet, quis porttitor tortor luctus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vehicula ante at odio maximus viverra. Vivamus commodo nulla elit, quis mollis magna eleifend vitae. Donec accumsan turpis dolor, eu euismod ipsum consequat sit amet. </p>
</asp:Content>